# Generated by Django 6.0.2 on 2026-03-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kineo', '0002_userprofile_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
