# Generated by Django 6.0.2 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kineo", "0003_remove_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
