# Generated by Django 6.0.2 on 2026-03-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kineo', '0004_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='country',
            field=models.CharField(default='Ukraine', max_length=100),
        ),
    ]
