# Generated by Django 6.0.2 on 2026-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kineo', '0007_favoritemovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seats', models.PositiveIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Зали',
                'ordering': ['name'],
            },
        ),
    ]
